services:
  app:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build: .
    # Nomeia o container para fácil identificação
    container_name: fastapi_escola_api
    # Mapeia a porta 8000 do host para a porta 8000 do container
    ports:
      - "8000:8000"
    # Mapeia o diretório atual para o diretório /app dentro do container
    # Isso tem dois benefícios principais:
    # 1. O arquivo do banco de dados (escola.db) será criado e persistido no seu diretório local.
    # 2. Quaisquer alterações no código-fonte serão refletidas imediatamente dentro do container,
    #    o que é ideal para desenvolvimento com o 'uvicorn --reload'.
    volumes:
      - .:/app


# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
